/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Ferramenta;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gustav
 */
public class CadastroFerramenta extends javax.swing.JFrame {

    private Ferramenta objFerramenta;

    /**
     * Creates new form CadastroFerramenta
     */
    public CadastroFerramenta() {
        initComponents();
        this.objFerramenta = new Ferramenta();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/617.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CampoMarca = new javax.swing.JTextField();
        CampoCusto = new javax.swing.JTextField();
        BtCadastrar = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Ferramenta");
        setMinimumSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 150, 37, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 180, 37, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Custo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 210, 37, 16);

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNome);
        CampoNome.setBounds(200, 150, 100, 22);

        CampoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(CampoMarca);
        CampoMarca.setBounds(200, 180, 100, 22);

        CampoCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCustoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCusto);
        CampoCusto.setBounds(200, 210, 71, 22);

        BtCadastrar.setText("Cadastrar");
        BtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtCadastrar);
        BtCadastrar.setBounds(290, 280, 90, 23);

        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtCancelar);
        BtCancelar.setBounds(100, 280, 90, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ferramentas.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMinimumSize(new java.awt.Dimension(542, 300));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
        // TODO add your handling code here:
        try {
            // recebendo e validando dados da interface gráfica.

            String nome = "";
            String marca = "";
            double custo = 0;

            if (this.CampoNome.getText().length() < 4) {
                throw new Mensagens("Nome deve conter ao menos 4 caracteres.");
            } else {
                nome = this.CampoNome.getText();
            }
            if (this.CampoMarca.getText().length() < 2) {
                throw new Mensagens("A marca deve conter ao menos 2 caracteres.");
            } else {
                marca = this.CampoMarca.getText();
            }
            if (this.CampoCusto.getText().length() == 0.00) {
                throw new Mensagens("O custo não pode ser zero.");
            } else {
                String custoString = this.CampoCusto.getText().replace(",", "."); // substitui vírgula por ponto
                custo = Double.parseDouble(custoString);
            }
            if (this.objFerramenta.InsertFerramentaBD(nome, marca, custo)) {
                JOptionPane.showMessageDialog(rootPane, "Ferramenta Cadastrada com Sucesso!");

                // limpa campos da interface
                this.CampoNome.setText("");
                this.CampoMarca.setText("");
                this.CampoCusto.setText("");
            }
            System.out.println(this.objFerramenta.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
//} catch (NumberFormatException erro2) {
//    JOptionPane.showMessageDialog(null, "Custo deve ser inserido com ponto no lugar da vírgula");
//} 
        } catch (SQLException ex) {
            Logger.getLogger(CadastroAmigo.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_BtCadastrarActionPerformed

    private void CampoCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCustoActionPerformed

    private void CampoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoMarcaActionPerformed

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFerramenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JTextField CampoCusto;
    private javax.swing.JTextField CampoMarca;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
