/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Amigo;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gustav
 */
public class GerenciaAmigo extends javax.swing.JFrame {

        private Amigo objAmigo;
    /**
     * Creates new form GerenciaAmigo
     */
    public GerenciaAmigo() {
        initComponents();
        this.objAmigo = new Amigo();
        this.carregaTabela();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/617.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaGerenciaA = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CampoTelefoneGerenciaA = new javax.swing.JTextField();
        CampoNomeGerenciaA = new javax.swing.JTextField();
        BtCancelarGerenciaA = new javax.swing.JButton();
        BtAlterarGerenciaA = new javax.swing.JButton();
        BtApagarGerenciaA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GerenciamentoA.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Amigos");
        setMinimumSize(new java.awt.Dimension(450, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        TabelaGerenciaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaGerenciaA.setShowGrid(false);
        TabelaGerenciaA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaGerenciaAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaGerenciaA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 369, 107);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 230, 37, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefone");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 250, 60, 16);

        CampoTelefoneGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneGerenciaAActionPerformed(evt);
            }
        });
        getContentPane().add(CampoTelefoneGerenciaA);
        CampoTelefoneGerenciaA.setBounds(150, 250, 125, 22);

        CampoNomeGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeGerenciaAActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNomeGerenciaA);
        CampoNomeGerenciaA.setBounds(150, 220, 187, 22);

        BtCancelarGerenciaA.setText("Cancelar");
        BtCancelarGerenciaA.setToolTipText("");
        BtCancelarGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarGerenciaAActionPerformed(evt);
            }
        });
        getContentPane().add(BtCancelarGerenciaA);
        BtCancelarGerenciaA.setBounds(80, 300, 90, 23);

        BtAlterarGerenciaA.setText("Alterar");
        BtAlterarGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarGerenciaAActionPerformed(evt);
            }
        });
        getContentPane().add(BtAlterarGerenciaA);
        BtAlterarGerenciaA.setBounds(190, 300, 80, 23);

        BtApagarGerenciaA.setText("Apagar");
        BtApagarGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtApagarGerenciaAActionPerformed(evt);
            }
        });
        getContentPane().add(BtApagarGerenciaA);
        BtApagarGerenciaA.setBounds(290, 300, 80, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GerenciamentoA.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, 0, 480, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaGerenciaAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaGerenciaAMouseClicked
        // TODO add your handling code here:
        if (this.TabelaGerenciaA.getSelectedRow() != -1) {

            String nome = this.TabelaGerenciaA.getValueAt(this.TabelaGerenciaA.getSelectedRow(), 1).toString();
            String telefone = this.TabelaGerenciaA.getValueAt(this.TabelaGerenciaA.getSelectedRow(), 2).toString();

            this.CampoNomeGerenciaA.setText(nome);
            this.CampoTelefoneGerenciaA.setText(telefone);



        }                                     
    }//GEN-LAST:event_TabelaGerenciaAMouseClicked

    private void CampoTelefoneGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneGerenciaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefoneGerenciaAActionPerformed

    private void BtCancelarGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarGerenciaAActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtCancelarGerenciaAActionPerformed

    private void BtAlterarGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarGerenciaAActionPerformed
        // TODO add your handling code here:
        try {
            // recebendo e validando dados da interface gr�fica.
            int id = 0;
            String nome = "";
            String telefone = "";

            if (this.CampoNomeGerenciaA.getText().length() < 2) {
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.CampoNomeGerenciaA.getText();
            }

            if (this.CampoTelefoneGerenciaA.getText().length() <10 || this.CampoTelefoneGerenciaA.getText().length() >11) {
                throw new Mensagens("Numero de telefone deve conter somente Numeros.");
            } else {
                telefone = this.CampoTelefoneGerenciaA.getText();
            }

            if (this.TabelaGerenciaA.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Amigo para Alterar");
            } else {
                id = Integer.parseInt(this.TabelaGerenciaA.getValueAt(this.TabelaGerenciaA.getSelectedRow(), 0).toString());
            }

            // envia os dados para o Aluno processar
            if (this.objAmigo.UpdateAmigoBD(nome,telefone,id)) {

                // limpa os campos
                this.CampoNomeGerenciaA.setText("");
                this.CampoTelefoneGerenciaA.setText("");
                JOptionPane.showMessageDialog(rootPane, "Amigo Alterado com Sucesso!");

            }
            System.out.println(this.objAmigo.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um numero.");
        } finally {
            carregaTabela(); // atualiza a tabela.
        }
   
    }//GEN-LAST:event_BtAlterarGerenciaAActionPerformed

    private void CampoNomeGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeGerenciaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeGerenciaAActionPerformed

    private void BtApagarGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtApagarGerenciaAActionPerformed
        // TODO add your handling code here:
        
         try {
            // validando dados da interface gr�fica.
            int id = 0;
            if (this.TabelaGerenciaA.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Amigo para APAGAR");
            } else {
                id = Integer.parseInt(this.TabelaGerenciaA.getValueAt(this.TabelaGerenciaA.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este Amigo ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Aluno processar
                if (this.objAmigo.DeleteAmigoBD(id)) {

                    // limpa os campos
                    this.CampoNomeGerenciaA.setText("");
                    this.CampoTelefoneGerenciaA.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Amigo Apagado com Sucesso!");

                }
            }
            System.out.println(this.objAmigo.getMinhaLista().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }//GEN-LAST:event_BtApagarGerenciaAActionPerformed

    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.TabelaGerenciaA.getModel();
        modelo.setNumRows(0);

        ArrayList<Amigo> minhalista = new ArrayList<>();
        minhalista = objAmigo.getMinhaLista();

        for (Amigo a : minhalista) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getTelefone(),

            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaAmigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterarGerenciaA;
    private javax.swing.JButton BtApagarGerenciaA;
    private javax.swing.JButton BtCancelarGerenciaA;
    private javax.swing.JTextField CampoNomeGerenciaA;
    private javax.swing.JTextField CampoTelefoneGerenciaA;
    private javax.swing.JTable TabelaGerenciaA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
