/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Ferramenta;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author gustav
 */
public class GerenciaFerramenta extends javax.swing.JFrame {

    private Ferramenta objFerramenta;

    /**
     * Creates new form GerenciaFerramenta
     */
    public GerenciaFerramenta() {
        initComponents();
        this.objFerramenta = new Ferramenta();
        this.carregaTabela();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/617.jpg")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaGerenciamentoF = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoNomeGerenciaF = new javax.swing.JTextField();
        CampoMarcaGerenciamentoF = new javax.swing.JTextField();
        CampoCustoGerenciamentoF = new javax.swing.JTextField();
        BtAlterarGerenciaF = new javax.swing.JButton();
        BtApagarGerenciamentoF = new javax.swing.JButton();
        BtCancelarGerenciaF = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Ferramentas");
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(408, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        TabelaGerenciamentoF.setBackground(new java.awt.Color(255, 255, 255));
        TabelaGerenciamentoF.setForeground(new java.awt.Color(0, 0, 0));
        TabelaGerenciamentoF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Marca", "Custo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaGerenciamentoF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaGerenciamentoFMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaGerenciamentoF);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 358, 116);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 200, 37, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 240, 37, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Custo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 280, 37, 16);
        getContentPane().add(CampoNomeGerenciaF);
        CampoNomeGerenciaF.setBounds(110, 200, 194, 22);
        getContentPane().add(CampoMarcaGerenciamentoF);
        CampoMarcaGerenciamentoF.setBounds(110, 240, 194, 22);

        CampoCustoGerenciamentoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCustoGerenciamentoFActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCustoGerenciamentoF);
        CampoCustoGerenciamentoF.setBounds(110, 280, 194, 22);

        BtAlterarGerenciaF.setText("Alterar");
        BtAlterarGerenciaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarGerenciaFActionPerformed(evt);
            }
        });
        getContentPane().add(BtAlterarGerenciaF);
        BtAlterarGerenciaF.setBounds(160, 320, 90, 23);

        BtApagarGerenciamentoF.setText("Apagar");
        BtApagarGerenciamentoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtApagarGerenciamentoFActionPerformed(evt);
            }
        });
        getContentPane().add(BtApagarGerenciamentoF);
        BtApagarGerenciamentoF.setBounds(280, 320, 90, 23);

        BtCancelarGerenciaF.setText("Cancelar");
        BtCancelarGerenciaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarGerenciaFActionPerformed(evt);
            }
        });
        getContentPane().add(BtCancelarGerenciaF);
        BtCancelarGerenciaF.setBounds(40, 320, 90, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GerenciamentoF.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-50, 0, 460, 470);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCancelarGerenciaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarGerenciaFActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtCancelarGerenciaFActionPerformed

    private void BtAlterarGerenciaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarGerenciaFActionPerformed
        // TODO add your handling code here:
        try {
            // recebendo e validando dados da interface gr�fica.
            int id = 0;
            String nome = "";
            String marca = "";
           // String custoString = this.TabelaGerenciamentoF.getValueAt(this.TabelaGerenciamentoF.getSelectedRow(), 3).toString();
            //custoString = custoString.replaceAll("[^\\d.,]", ""); // Remove caracteres não numéricos, exceto ponto e vírgula
            double custo;
            
//            try {
//                custo = Double.parseDouble(custoString.replace(",", ".")); // Substitui a vírgula pelo ponto para representar o separador decimal
//            } catch (NumberFormatException e) {
//                // Lidar com a exceção de formato inválido aqui
//                e.printStackTrace();
//            }

            if (this.CampoNomeGerenciaF.getText().length() < 2) {
                throw new Mensagens("Nome deve conter ao menos 2 letras.");
            } else {
                nome = this.CampoNomeGerenciaF.getText();
            }

            if (this.CampoMarcaGerenciamentoF.getText().length() < 2) {
                throw new Mensagens("A marca deve ter ao menos 2 letras");
            } else {
                marca = this.CampoMarcaGerenciamentoF.getText();
            }
           if (this.CampoCustoGerenciamentoF.getText().length() == 0.00) {
                throw new Mensagens("O custo não pode ser zero.");
            } else {
                String custoString = this.CampoCustoGerenciamentoF.getText().replace(",", "."); // substitui vírgula por ponto
                custo = Double.parseDouble(custoString);
            }

            if (this.TabelaGerenciamentoF.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Aluno para Alterar");
            } else {
                id = Integer.parseInt(this.TabelaGerenciamentoF.getValueAt(this.TabelaGerenciamentoF.getSelectedRow(), 0).toString());
            }

            // envia os dados para o Aluno processar
            if (this.objFerramenta.UpdateFerramentaBD(nome, marca, custo, id)) {

                // limpa os campos
                this.CampoNomeGerenciaF.setText("");
                this.CampoMarcaGerenciamentoF.setText("");
                this.CampoCustoGerenciamentoF.setText("");
                JOptionPane.showMessageDialog(rootPane, "Ferramenta Alterada com Sucesso!");

            }
            System.out.println(this.objFerramenta.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Formato nao aceito.");
        } finally {
            carregaTabela(); // atualiza a tabela.
        }
    }//GEN-LAST:event_BtAlterarGerenciaFActionPerformed

    private void BtApagarGerenciamentoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtApagarGerenciamentoFActionPerformed
        // TODO add your handling code here:
        try {
            // validando dados da interface gr�fica.
            int id = 0;
            if (this.TabelaGerenciamentoF.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione uma Ferramenta para APAGAR");
            } else {
                id = Integer.parseInt(this.TabelaGerenciamentoF.getValueAt(this.TabelaGerenciamentoF.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR esta Ferramenta ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Aluno processar
                if (this.objFerramenta.DeleteFerramentaBD(id)) {

                    // limpa os campos
                    this.CampoNomeGerenciaF.setText("");
                    this.CampoMarcaGerenciamentoF.setText("");
                    this.CampoCustoGerenciamentoF.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Ferramenta apagada com sucesso!");

                }
            }
            System.out.println(this.objFerramenta.getMinhaLista().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }//GEN-LAST:event_BtApagarGerenciamentoFActionPerformed

    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.TabelaGerenciamentoF.getModel();
        modelo.setNumRows(0);

        ArrayList<Ferramenta> minhalista = new ArrayList<>();
        minhalista = objFerramenta.getMinhaLista();

        for (Ferramenta a : minhalista) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getMarca(),
                a.getCustoFormatado(),});

        }
    }

    /**
     * @param args the command line arguments
     */

    private void TabelaGerenciamentoFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaGerenciamentoFMouseClicked
        // TODO add your handling code here:
        if (this.TabelaGerenciamentoF.getSelectedRow() != -1) {

            String nome = this.TabelaGerenciamentoF.getValueAt(this.TabelaGerenciamentoF.getSelectedRow(), 1).toString();
            String marca = this.TabelaGerenciamentoF.getValueAt(this.TabelaGerenciamentoF.getSelectedRow(), 2).toString();
            String custoString = this.TabelaGerenciamentoF.getValueAt(this.TabelaGerenciamentoF.getSelectedRow(), 3).toString();
            double custo = Double.parseDouble(custoString.replaceAll("[^\\d.,]", "").replaceAll("\\s+", "").replace(",", "."));


            String custoSemSimbolo = custoString.replaceAll("[^\\d.,]", "").replaceAll("\\s+", "");

            // Substituir vírgulas por pontos
            String custoFormatado = custoSemSimbolo.replace(",", ".");

            // Verificar se há múltiplos pontos decimais
            int countPontos = custoFormatado.length() - custoFormatado.replace(".", "").length();
            if (countPontos > 1) {
                // Remover todos os pontos, exceto o último
                int lastIndex = custoFormatado.lastIndexOf(".");
                custoFormatado = custoFormatado.substring(0, lastIndex) + custoFormatado.substring(lastIndex + 1).replace(".", "");
            }


            try {
                custo = Double.parseDouble(custoFormatado);
            } catch (NumberFormatException e) {
                e.printStackTrace();
            }

            this.CampoNomeGerenciaF.setText(nome);
            this.CampoMarcaGerenciamentoF.setText(marca);
            this.CampoCustoGerenciamentoF.setText(custoSemSimbolo);

        }
    }//GEN-LAST:event_TabelaGerenciamentoFMouseClicked

    private void CampoCustoGerenciamentoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCustoGerenciamentoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCustoGerenciamentoFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaFerramenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterarGerenciaF;
    private javax.swing.JButton BtApagarGerenciamentoF;
    private javax.swing.JButton BtCancelarGerenciaF;
    private javax.swing.JTextField CampoCustoGerenciamentoF;
    private javax.swing.JTextField CampoMarcaGerenciamentoF;
    private javax.swing.JTextField CampoNomeGerenciaF;
    private javax.swing.JTable TabelaGerenciamentoF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
