/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author gustav
 */
public class SINERGY extends javax.swing.JFrame {

    /**
     * Creates new form SINERGY
     */
    public SINERGY() {
        initComponents();
        //Mudando icone
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/617.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtCadastrarA = new javax.swing.JButton();
        BtGerenciarA = new javax.swing.JButton();
        BtCadastrarF = new javax.swing.JButton();
        BtGerenciarF = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SINERGY");
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ferramentas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 280, 110, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Amigos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 280, 80, 25);

        BtCadastrarA.setText("Cadastrar");
        BtCadastrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarAActionPerformed(evt);
            }
        });
        getContentPane().add(BtCadastrarA);
        BtCadastrarA.setBounds(340, 330, 100, 23);

        BtGerenciarA.setText("Gerenciar");
        BtGerenciarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGerenciarAActionPerformed(evt);
            }
        });
        getContentPane().add(BtGerenciarA);
        BtGerenciarA.setBounds(340, 370, 100, 23);

        BtCadastrarF.setText("Cadastrar");
        BtCadastrarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarFActionPerformed(evt);
            }
        });
        getContentPane().add(BtCadastrarF);
        BtCadastrarF.setBounds(74, 326, 100, 23);

        BtGerenciarF.setText("Gerenciar");
        BtGerenciarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGerenciarFActionPerformed(evt);
            }
        });
        getContentPane().add(BtGerenciarF);
        BtGerenciarF.setBounds(74, 367, 100, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/infinity tech def.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -260, 500, 940);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadastrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarAActionPerformed
        // TODO add your handling code here:
        CadastroAmigo objeto = new CadastroAmigo();
        objeto.setVisible(true);
    }//GEN-LAST:event_BtCadastrarAActionPerformed

    private void BtGerenciarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGerenciarAActionPerformed
        // TODO add your handling code here:
                GerenciaAmigo objeto = new GerenciaAmigo();
        objeto.setVisible(true);
    }//GEN-LAST:event_BtGerenciarAActionPerformed

    private void BtCadastrarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarFActionPerformed
        // TODO add your handling code here:
        CadastroFerramenta objeto = new CadastroFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_BtCadastrarFActionPerformed

    private void BtGerenciarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGerenciarFActionPerformed
        // TODO add your handling code here:
        GerenciaFerramenta objeto = new GerenciaFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_BtGerenciarFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SINERGY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SINERGY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SINERGY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SINERGY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SINERGY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrarA;
    private javax.swing.JButton BtCadastrarF;
    private javax.swing.JButton BtGerenciarA;
    private javax.swing.JButton BtGerenciarF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
